services:

  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: unless-stopped

    volumes:
      - waha_data:/app/.sessions

    environment:
      WAHA_API_KEY: ${WAHA_API_KEY}
      WHATSAPP_HOOK_URL: http://api:8000/webhook
      WAHA_URL: http://waha:3000
      WHATSAPP_HOOK_EVENTS: message

  api:
    container_name: api

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

volumes:
  waha_data: