name: Deploy VPS

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Atualizar VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Conectado na VPS"
            echo "Servidor: $(hostname)"
            echo "Usuário: $(whoami)"

            cd ../opt/lang

            echo "Atualizando código..."
            git pull origin main

            echo "Código atualizado!"

            docker --version